### ISSUE TITLE
forward中のyiとnext_yiの使い方について

### ISSUE THREAD

**Issue by yuma-long** [Matsushima-lab/FLSA#5]
flsa_dp.py中80、81行目の
```python
next_bm = yi - lamb
next_bp = yi + lamb
```
と86、88行目の
```python
next_e_ac = -next_yi
next_a_c_list = [fac + next_e_ac for fac in next_f_a_c_list]
```
はどちらかだけでいい気がします。つまり86、88行目を入れないか、

```python
next_bm = - lamb
next_bp = + lamb
~~~
next_e_ac = -next_yi
next_a_c_list = [fac + next_e_ac for fac in next_f_a_c_list]
```
とするかです。片方やれば計算に折り込まれるはずなので。。。

個人的には各```Deltafunc```インスタンスが全ての区間における傾きと切片を保持しているのを明示的にするために後者を採用して$\delta_0$については```main```で
```python
delta_squared[0] = DeltaSquared(
        knots=[], bm=None, bp=None, a_b_list=[1], a_c_list=[-y[0]]
    )
```
とした方が統一的になるかなと思います。

**Comment by yuma-long** [comment]
後者の方がいいというより```main```の修正込みで後者でなければいけない理由がしてきました。それでないと $y_1$ が $\delta_2$ 以降の $\delta$ に考慮されないので

**Comment by smatsus** [comment]
ブランチを切って改善案をpull requestしてください。
